// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inventory struct {
	ProductID      int32
	WarehouseID    int32
	StockLevel     int32
	AlertThreshold int32
}

type Product struct {
	ProductID   int32
	Name        string
	Description pgtype.Text
	Price       pgtype.Numeric
}

type StockLog struct {
	LogID         int32
	ProductID     int32
	WarehouseID   int32
	PreviousStock int32
	UpdatedStock  int32
	Timestamp     pgtype.Timestamp
}

type Warehouse struct {
	WarehouseID int32
	Name        string
	Location    pgtype.Text
}
